DROP TABLE IF EXISTS XHYMsg;

CREATE TABLE IF NOT EXISTS XHYMsg(pk INTEGER PRIMARY KEY autoincrement,account TEXT NOT NULL,deviceNwkAddr TEXT NOT NULL,msgType INTEGER,msgDate TEXT,alarmValue INTEGER);

